# Generated by Django 2.2.5 on 2020-11-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_auto_20201111_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Messages',
        ),
    ]
